- name: Check whether there's any old configuration
  stat:
    path: "/srv/{{ rss_hostname }}/config.php"
  register: ttrss_db_config

- block:
  - name: Generate password
    command: mkpasswd -l 20 -s 0
    register: mariadb_ttrss_pass_generated
    no_log: true

  - name: Generate password
    set_fact:
      mariadb_ttrss_pass: "{{ mariadb_ttrss_pass_generated.stdout }}"

  - name: Create ttrss DB user
    mysql_user:
      name: tinyrss
      host: "{{ item }}"
      password: "{{ mariadb_ttrss_pass }}"
      priv: "tinyrss.*:ALL"
      state: present
    with_items:
    - 127.0.0.1
    - localhost

  - lineinfile:
      path: "/srv/{{ rss_hostname }}/config.php.tpl"
      regexp: "define..DB_PASS.."
      line: " define('DB_PASS', '{{ mariadb_ttrss_pass }}');"

  - name: Create config.php
    command: mv /srv/{{ rss_hostname }}/config.php.tpl /srv/{{ rss_hostname }}/config.php
    args:
      creates: /srv/{{ rss_hostname }}/config.php

  when: ttrss_db_config.stat.exists == false

- name: Make sure Nginx can connect to DB
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
  - httpd_can_network_connect
  - httpd_can_network_connect_db