- name: Check if directory exists
  stat:
    path: "/srv/{{ rss_hostname }}"
  register: www_directory

- block:
  - name: Download web backup from Cloud storage
    # not using ansible gc_storage module as it doesn't support
    # service-account/IAM roles authentication that are assigned to
    # GCE instances
    command: gsutil cp gs://{{ gcp.cloud_storage_bucket_name }}/backups/{{ rss_hostname }}-latest.tar.gz /srv/{{ rss_hostname }}-latest.tar.gz
    changed_when: false

  - name: Unarchive backup
    unarchive:
      dest: /srv
      owner: nginx
      group: nginx
      mode: 0770
      src: "/srv/{{ rss_hostname }}-latest.tar.gz"

  - name: Cleanup
    file:
      path: "/srv/{{ rss_hostname }}-latest.tar.gz"
      state: absent

  - name: Rename old config.php
    command: mv /srv/{{ rss_hostname }}/config.php /srv/{{ rss_hostname }}/config.php.tpl
    args:
      creates: "/srv/{{ rss_hostname }}/config.php.tpl"

  when: www_directory.stat.exists == false

- name: Fix SELinux labels
  file:
    path: "/srv/{{ rss_hostname }}"
    setype: "httpd_sys_content_t"
    recurse: yes
    state: directory

- name: Fix SELinux labels
  file:
    path: "{{ item.path }}"
    setype: "{{ item.setype }}"
    recurse: yes
    state: directory
  with_items:
  - { path: '/srv/{{ rss_hostname }}/cache', setype: 'httpd_sys_content_rw_t'}
  - { path: '/srv/{{ rss_hostname }}/lock', setype: 'httpd_sys_content_rw_t'}
  - { path: '/srv/{{ rss_hostname }}/feed-icons', setype: 'httpd_sys_content_rw_t'}