- name: Download web backup from Cloud storage
  gc_storage:
    bucket: "{{ gcp.cloud_storage_bucket_name }}"
    object: backups/rss.lasyk.info-latest.tar.gz
    dest: /srv/rss.lasyk.info-latest.tar.gz
    mode: get

- name: Unarchive backup
  unarchive:
    dest: /srv
    owner: nginx
    group: nginx
    mode: 0770
    src: /srv/rss.lasyk.info-latest.tar.gz

- name: Cleanup
  file:
    path: /srv/rss.lasyk.info-latest.tar.gz
    state: absent